events:
  - https://github.com/knative-party/site/raw/main/events/toc-review.rotation
rotations:
  - https://raw.githubusercontent.com/knative/serving/main/support/support.rotation
  - https://raw.githubusercontent.com/knative/eventing/main/support/support.rotation
  - https://github.com/knative-party/site/raw/main/rotations/security.rotation